#########################################################################
                              # BASE
#########################################################################
#########################################################################
base:
  image: 'gantry-admin://images/default.jpg'
  description: 'base'
  colors:
    - ''
    - ''
    - ''
    - ''

  styles:
                                                    ## CORE ##
## ############################ CORE ####################################

#########################################################################
    accent:
    ## Activar panel
      panel:                                             '1' # 1 activar

## ####################  Rueda Cromática color
      rueda-cromatica:                                   'ryb' # ryb rgb
      girar-rueda:                                       '' #   (0%)  180%  360%
      armonia:                                           '0' #
    # 0 Gantry, 1 Monocromático, 2 Análogo, 3 Triada, 4 Complementario,
    # 5 Complementario-div, 6 Tetra
      color-base:                                        '' # Obligatorio para la armonía

      monocontraste:                                     '' # OBLIGATORIO PORCENTAJE %
      mono-color2:                                       '' # accento color en Monocromático

    ## Colores
      color-1:                                           ''
      color-2:                                           ''
      color-3:                                           ''
      color-4:                                           ''

    ## Grises
      contrastegris:                                     '' # OBLIGATORIO PORCENTAJE %
      color-5:                                           ''
      color-6:                                           ''
      color-7:                                           ''
      color-8:                                           ''


## ####################   Parámetros globales
      activar-glob:                                      '' # 1 activar

      saturar-global:                                    '' # %  0%  (50%)  100% pastel
      claridad-global:                                   '' # %  0%  (50%)  100%


  ## #################### Parámetros individuales


      color2-efect:                                      '' # 1 activar
      color-2-saturar:                                   ''  #  0  25  (50) 75  100
      color-2-claridad:                                  ''  #  0  25  (50) 75  100

      color3-efect:                                      '' # 1 activar
      color-3-saturar:                                   ''
      color-3-claridad:                                  ''

      color4-efect:                                      '' # 1 activar
      color-4-saturar:                                   ''
      color-4-claridad:                                  ''

    base:
## #################### Tipografía
      heading-font:                                      '' # 1 Fuente para títulos
      body-font:                                         '' # 2 Fuente para textos
      extra-font:                                        '' # 3 Fuente  extra tdweb

## Color botón Slider
      slider_btn:                                        '' # color fondo botón
      slider_btn__hover:                                 ''
      slider_btn_texto:                                  '' # color texto botón
      slider_btn_texto_hover:                            ''





                                                               ## BODY ##
## ############################ BODY ####################################

#########################################################################
    body:

## color
      background:                                        '' #
      background_efecto:                                 '' # 1
      background_efectovalor:                            ''
## imagen
      background_image:                                  '' # gantry-media:##presets/default/image.jpg
      background_repeat:                                 '' # repeat, no-repeat, repeat-x, repeat-y
      background_size:                                   '' # auto, contain, cover
      background_position:                               '' # 100px 20px
