name: 13
timestamp: 1448915936
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1448915936
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
